# OPEN CV2.

Opencv is a python wrapper used in machine learning, computer vision, and image processing. This module is commonly used for object detection in images and videos. When intergrated with other open source python libraries such as numpy and  matplotlib it can be optimized for powerful tasks sucj as face and handwritten notes detection.



## 1. Basic Operations.

In [19]:
# Import modules

import cv2 
import numpy as np 
import matplotlib as plt

import warnings
warnings.filterwarnings('ignore')

In [20]:
# Read cat images. 
path = "F:\Programs\Secrets of ML\ML Github\Machine-Learning\Data\Image samples"

#cat1 = cv2.imread("Data/Image samples/cat1.png", 0)
#print(cat1.shape())

# To read image from disk in grey band 
img = cv2.imread(path + "\calf1.jpg", 0)
print(img)
 


[[171 167 163 ... 241 216 201]
 [170 170 168 ... 237 213 202]
 [158 167 172 ... 234 213 207]
 ...
 [113 119 110 ... 154 162 166]
 [125 121 120 ... 148 155 158]
 [122 122 127 ... 146 152 155]]


Current Directory f:\Programs\Secrets of ML\ML Github\Machine-Learning\Notebooks\Image_Processing
..
