# OPEN CV2.

Opencv is a python wrapper used in machine learning, computer vision, and image processing. This module is commonly used for object detection in images and videos. When intergrated with other open source python libraries such as numpy and  matplotlib it can be optimized for powerful tasks sucj as face and handwritten notes detection.



## 1. Basic Operations.

In [20]:
# Import modules

import cv2 
import numpy as np 
import matplotlib as plt
from copy import deepcopy

import warnings
warnings.filterwarnings('ignore')

In [23]:
# Read cat images. 
path = "F:\Programs\Secrets of ML\ML Github\Machine-Learning\Data\Image samples"

#cat1 = cv2.imread("Data/Image samples/cat1.png", 0)
#print(cat1.shape())

# To read image from disk in grey band 
img = cv2.imread(path + "\cat1.png", 0)
print(f'Image array : \n{img} \n\n Shape (height * width) : {img.shape}')

# Read pixel value of the third row , third column , indexing starts at 0 
print(f'Pixel in r3 c3 : {img[2,2]}')


 


Image array : 
[[170 173 177 ... 190 190 190]
 [170 173 177 ... 190 190 190]
 [173 175 179 ... 190 190 190]
 ...
 [184 207 226 ... 227 235 243]
 [179 195 206 ... 231 239 247]
 [173 182 184 ... 233 241 249]] 

 Shape (height * width) : (288, 216)
Pixel in r3 c3 : 179


In [24]:
# Display a function to display image in a window 


# Function
def wind(img):
    # 1.Define window nmae and its size 
    cv2.namedWindow("image", cv2.WINDOW_NORMAL)

    # 2. Create window to display 
    cv2.imshow("image", img)

    # 3. Hold window for 5 sec or 5000 miliseconds
    # If value is 0 the window will be indefinate  
    cv2.waitKey(0)

    # 4. Remove the gui from the screen 
    cv2.destroyAllWindows()


# Call function 
wind(img)

In [25]:
# Display image in RGB format 

cat1 = cv2.imread(path + "\cat1.png", 1)
wind(cat1)

print(cat1.shape)

(288, 216, 3)


In [28]:
# Draw a circle at coordinates 100, 120

# Create a copy of the image to prevent repeated circle drawings 
cat1_cpy = deepcopy(cat1)
# Define center coordinates, circle radius, colour combination(BGR format), and thicknes
circle1 = cv2.circle(cat1_cpy, (100, 120), 50, (20, 10, 200), 10)
wind(circle1)